### ISSUE TITLE
[BUG 🐞] Fix mobile responsiveness for attendance page

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#136]
### Description

- Fix the paper component to look better for mobile devices.

### Screenshots

![Screenshot_2023-09-19-02-31-46-992_com android chrome](https://github.com/warmachine028/uemcrp/assets/75939390/c7432a98-d1bc-43fd-81ac-248b38d3f11c)

### Additional information

- Maintain Folder Structure
- Always use styled componets and MUI components instead of plain CSS.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Sky-De** [comment]
@warmachine028 please assign this to me , i would work on this 
thanks

**Comment by warmachine028** [comment]
Assigning you

**Comment by Sky-De** [comment]
@warmachine028 i will start working on this now, if you got any design or suggestions please share with me now, not after the work is done
thanks for underastanding

**Comment by warmachine028** [comment]
Yes I understand
- To access this page type any random 12 digit code

## Suggession
- Do not change the Navbar
- Work only in the disturbed component.
- Make sure the view is only changed for mobile devices
- The view for other larger devices must not be hampered
- Use Styled components and MUI components only.

**Comment by Sky-De** [comment]
@warmachine028 check this please

## What did i do ?
As  you asked, i did not change anything except fixing responsiveness issue only with one line of code which added to styles of coresponding component

if you got any idea about design content like shapes or colors , share with me to implement those changes, otherwise let me know to send PR for this
thanks

## SCREEN SHOTS

**Mobile**


![showM](https://github.com/warmachine028/uemcrp/assets/79264045/e27cfd07-62e2-43ea-b175-74dcf483ad2e)



**Desktop**

![showD](https://github.com/warmachine028/uemcrp/assets/79264045/325eb1c9-dcb5-4824-a8ec-178e67691616)

**Comment by warmachine028** [comment]
Yes only this fix looks Good for now
