### ISSUE TITLE
Make changes in University Marking System

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/uemcrp#81]
### Description

- Make the Top Paper component expand to both sides
- Increase the height of the paper component
- The Label `Student Marks Display` Must go to the top of the page
- The table component must expand both sides

### Screenshots

- Changes requested
![Screenshot 2022-10-05 104434](https://user-images.githubusercontent.com/75939390/193986880-ab9450e5-7a39-48e5-a6ac-21dd09a66229.png)

- Take reference from this component
![Screenshot 2022-10-05 104731](https://user-images.githubusercontent.com/75939390/193986672-7adfcfd9-2afe-4019-ae26-95ef576b34dc.png)

### Additional information

- Only use material UI components.
- Do not install any new Package.
- Make changes to the required file only.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Ritesh-Dabral** [comment]
@warmachine028 
Can u assign this to me ?

**Comment by warmachine028** [comment]
yes! Assigning You

**Comment by Ritesh-Dabral** [comment]
@warmachine028 

Please verify


- Stuent Marks Display and semester selection on the top
- Increased the Width of Paper Component but kept a limit else on bigger screen sizes, it won't look good due to justify-content set to space-between
- Increased the size of result to cover the parent 
- Increased height of Top Paper

![image](https://user-images.githubusercontent.com/36252036/193999184-3dfcbbc8-db2c-4b2d-bcfc-14728e086fe9.png)

**Comment by warmachine028** [comment]
All looks Good!
Just 2 changes required
- Can you make the paper width same as the table?
- Increase the semester drop-down width to double its current size

Good Job! 🎊

**Comment by Ritesh-Dabral** [comment]
@warmachine028 
Please verify
- Stuent Marks Display and semester selection on the top
- Increased the Width of Paper Component but kept a limit else on bigger screen sizes, it won't look good due to justify-content set to space-between
- Increased the size of result to cover the parent
- Increased height of Top Paper
- Paper width same as the table
- Increase the semester drop-down width to double its current size

![image](https://user-images.githubusercontent.com/36252036/194001349-0d85bd2d-9f0b-44e1-a900-45f3f6f63224.png)

**Comment by warmachine028** [comment]
Great now create a PR
